### PR TITLE
Split up texts that are too long into multiple requests. Fixes #9

### LINKED ISSUE #9: Translate texts longer than 2000 bytes
Hi there,

The Google API allows for a maximum of 2K characters per query, if you're using GET. See here:
https://cloud.google.com/translate/v2/using_rest#detect-WorkingResults

If you want to translate longer texts, one solution is to split it up into multiple queries. The split should be done at key characters, such as newlines (end of paragraphs), dots (end of sentences) or at worst at spaces (end of a word). I am going to submit a pull request for an implementation soon.

Another solution would be to use POST instead of GET, which apparently raises this limit to 5K characters.

Cheers!

### PR DESCRIPTION
**Pull request by liviucmg**

### CODE REVIEW

**Comment by eko** [comment]
Hi @liviucmg,

Thank you so much for this great addition!

However, unit tests are failing. Could you please provide some test cases of this feature?

Thank you!

**Comment by liviucmg** [comment]
From what I've seen, some tests are failing because of an outdated version
of composer, not sure what I can do about that. Or did I miss something?
Thanks!

**Comment by eko** [comment]
@liviucmg I've updated `composer.json` to fix the `guzzlehttp/guzzle` required version for PHP <= 5.4.0 (this is the reason why Travis is failing for PHP 5.3).

Can you please rebase this PR?

Thank you

**Comment by eko** [comment]
Hi @liviucmg,

Is there any chance to get this PR merged? :)

Thank you for your work!

**Comment by liviucmg** [comment]
Hi @eko ,
Definitely want to get this merged and add some tests, just couldn't find the time. Will get back to you shortly, I hope. :)
Thanks.

**Comment by liviucmg** [comment]
One question @eko : How do I get the tests running? I have tried PHPUnit 5.x, PHPUnit 4.8.x, and PHPUnit 4.5.x (what you appear to be running on Travis), and all of them fail with the following:

    ReflectionException: Class Mock_Detector_3239176c does not have a constructor, so you cannot pass any constructor arguments

That error message is for each test method. So, basically I wrote the test, but cannot run it to test it. :) Maybe it's the PHP version I am using - 5.6.13?

**Comment by eko** [comment]
Hi @liviucmg,

It looks like tests are passing here with PHPUnit 4.5.0 and PHP 5.6.5: https://travis-ci.org/eko/GoogleTranslateBundle/jobs/76175026

Can you please paste the full PHPUnit error stacktrace?

Thank you

**Comment by liviucmg** [comment]
Sure @eko, here it is:

```
vendor/phpunit/phpunit/phpunit -c app 
PHPUnit 4.5.1 by Sebastian Bergmann and contributors.

Configuration read from /home/liviu/synced-storage/work/symfonydev/app/phpunit.xml.dist

EEEEEEEEE.

Time: 287 ms, Memory: 5.50Mb

There were 9 errors:

1) Eko\GoogleTranslateBundle\Tests\Method\DetectorTest::testSimpleDetect
ReflectionException: Class Mock_Detector_c14f9b75 does not have a constructor, so you cannot pass any constructor arguments

/home/liviu/synced-storage/work/GoogleTranslateBundle/Tests/Method/DetectorTest.php:33

2) Eko\GoogleTranslateBundle\Tests\Method\DetectorTest::testExceptionDetect
ReflectionException: Class Mock_Detector_c14f9b75 does not have a constructor, so you cannot pass any constructor arguments

/home/liviu/synced-storage/work/GoogleTranslateBundle/Tests/Method/DetectorTest.php:33

3) Eko\GoogleTranslateBundle\Tests\Method\LanguagesTest::testSimpleGet
ReflectionException: Class Mock_Languages_eae40848 does not have a constructor, so you cannot pass any constructor arguments

/home/liviu/synced-storage/work/GoogleTranslateBundle/Tests/Method/LanguagesTest.php:33

4) Eko\GoogleTranslateBundle\Tests\Method\LanguagesTest::testGetWithTarget
ReflectionException: Class Mock_Languages_eae40848 does not have a constructor, so you cannot pass any constructor arguments

/home/liviu/synced-storage/work/GoogleTranslateBundle/Tests/Method/LanguagesTest.php:33

5) Eko\GoogleTranslateBundle\Tests\Method\TranslatorTest::testSimpleTranslate
ReflectionException: Class Mock_Translator_edeb0c72 does not have a constructor, so you cannot pass any constructor arguments

/home/liviu/synced-storage/work/GoogleTranslateBundle/Tests/Method/TranslatorTest.php:33

6) Eko\GoogleTranslateBundle\Tests\Method\TranslatorTest::testMultipleTranslate
ReflectionException: Class Mock_Translator_edeb0c72 does not have a constructor, so you cannot pass any constructor arguments

/home/liviu/synced-storage/work/GoogleTranslateBundle/Tests/Method/TranslatorTest.php:33

7) Eko\GoogleTranslateBundle\Tests\Method\TranslatorTest::testMultipleEconomicTranslate
ReflectionException: Class Mock_Translator_edeb0c72 does not have a constructor, so you cannot pass any constructor arguments

/home/liviu/synced-storage/work/GoogleTranslateBundle/Tests/Method/TranslatorTest.php:33

8) Eko\GoogleTranslateBundle\Tests\Method\TranslatorTest::testTranslateUsingDetector
ReflectionException: Class Mock_Translator_edeb0c72 does not have a constructor, so you cannot pass any constructor arguments

/home/liviu/synced-storage/work/GoogleTranslateBundle/Tests/Method/TranslatorTest.php:33

9) Eko\GoogleTranslateBundle\Tests\Method\TranslatorTest::testLongTranslate
ReflectionException: Class Mock_Translator_edeb0c72 does not have a constructor, so you cannot pass any constructor arguments

/home/liviu/synced-storage/work/GoogleTranslateBundle/Tests/Method/TranslatorTest.php:33
                                    
FAILURES!                           
Tests: 10, Assertions: 2, Errors: 9.
```

Thank you for your help.

**Comment by liviucmg** [comment]
Ignore that, I was running the tests wrong. I did a `composer update` and `phpunit` directly into the bundle folder, and now everything is fine.

**Comment by liviucmg** [comment]
Hi @eko, I have added a test, fixed a bug in my previous commit, squashed the two commits, and rebased. Hope the Travis test passes.

**Comment by eko** [comment]
@liviucmg Well done! Thank you! :)

**Comment by liviucmg** [comment]
Thank you as well. :)

**Pull request merged**
